// examples/frameworks/vue/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { initializeWebMCPPolyfill } from "@mcp-b/webmcp-polyfill";

onMounted(() => {
  initializeWebMCPPolyfill();

  navigator.modelContext.registerTool({
    name: "current_route",
    description: "Returns the current route path",
    inputSchema: {
      type: "object",
      properties: {},
    },
    execute: async () => ({
      content: [{ type: "text", text: window.location.pathname }],
    }),
  });
});
</script>

<template>
  <p>WebMCP tool "current_route" registered.</p>
</template>

// examples/frameworks/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { initializeWebMCPPolyfill } from '@mcp-b/webmcp-polyfill';

  onMount(() => {
    initializeWebMCPPolyfill();

    navigator.modelContext.registerTool({
      name: 'ping',
      description: 'Returns pong',
      inputSchema: {
        type: 'object',
        properties: {},
      },
      execute: async () => ({
        content: [{ type: 'text', text: 'pong' }],
      }),
    });
  });
</script>

<p>WebMCP tool "ping" registered.</p>
