// examples/frameworks/svelte/src/App.svelte
<script lang="ts">
import { installWebMCP } from '@mcp-b/webmcp-polyfill';
import { onMount } from 'svelte';

onMount(async () => {
  installWebMCP();
  if (!document.modelContext) throw new Error('WebMCP is unavailable');

  await document.modelContext.registerTool({
    name: 'get_info',
    description: 'Returns basic app info',
    inputSchema: {
      type: 'object',
      properties: {},
    },
    execute: async () => ({
      content: [{ type: 'text', text: 'Svelte app is running' }],
    }),
  });
});
</script>

<p>WebMCP tool "get_info" registered.</p>

// examples/frameworks/nextjs/app/page.tsx
'use client';

import { installWebMCP } from '@mcp-b/webmcp-polyfill';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    installWebMCP();
    if (!document.modelContext) throw new Error('WebMCP is unavailable');

    void document.modelContext.registerTool({
      name: 'get_status',
      description: 'Returns app status',
      inputSchema: {
        type: 'object',
        properties: {},
      },
      execute: async () => ({
        content: [{ type: 'text', text: 'Next.js app is running' }],
      }),
    });
  }, []);

  return <p>WebMCP tool "get_status" registered.</p>;
}
