// examples/frameworks/angular/src/app/app.ts
import { Component, type OnInit } from '@angular/core';
import { installWebMCP } from '@mcp-b/webmcp-polyfill';

@Component({
  selector: 'app-root',
  template: '<p>WebMCP tool "get_status" registered.</p>',
})
export class App implements OnInit {
  async ngOnInit() {
    installWebMCP();
    if (!document.modelContext) throw new Error('WebMCP is unavailable');

    await document.modelContext.registerTool({
      name: 'get_status',
      description: 'Returns app status',
      inputSchema: {
        type: 'object',
        properties: {},
      },
      execute: async () => ({
        content: [{ type: 'text', text: 'Angular app is running' }],
      }),
    });
  }
}

// examples/frameworks/nextjs/app/page.tsx
'use client';

import { installWebMCP } from '@mcp-b/webmcp-polyfill';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    installWebMCP();
    if (!document.modelContext) throw new Error('WebMCP is unavailable');

    void document.modelContext.registerTool({
      name: 'get_status',
      description: 'Returns app status',
      inputSchema: {
        type: 'object',
        properties: {},
      },
      execute: async () => ({
        content: [{ type: 'text', text: 'Next.js app is running' }],
      }),
    });
  }, []);

  return <p>WebMCP tool "get_status" registered.</p>;
}
